[template]
src = "consul.key.tmpl"
dest = "/opt/rancher/ssl/consul.key"
owner = "root"
mode = "0644"
keys = [
  "/stacks/consul/services/server/metadata/consul1.key",
  "/stacks/consul/services/server/metadata/consul2.key",
  "/stacks/consul/services/server/metadata/consul3.key",
  "/self/container/service_index",
]
