[template]
prefix = "/self"
src = "consul.key.tmpl"
dest = "/app/config/consul.key"
owner = "root"
mode = "0644"
keys = [
  "/stack/services/server/metadata/consul1.key",
  "/stack/services/server/metadata/consul2.key",
  "/stack/services/server/metadata/consul3.key",
  "/container/service_index",
]
