[template]
prefix = "/self"
src = "server.json.tmpl"
dest = "/opt/rancher/config/server.json"
owner = "root"
mode = "0644"
keys = [
  "/container/primary_ip",
  "/stack/services/server/metadata/enc.key",
  "/stack/services/server/scale",
]
