[template]
src = "server.json.tmpl"
dest = "/opt/rancher/config/server.json"
owner = "root"
mode = "0644"
keys = [
  "/self/service/containers/0/name",
  "/containers",
  "/self/container/name",
  "/self/container/primary_ip",
  "/stacks/consul/services/server/metadata/enc.key",
  "/stacks/consul/services/server/containers",
  "/self/container/service_index",
  "/self/stack/services/server/scale",
  "/self/stack/services/server/containers",
]
